### ISSUE TITLE
Update docs to tell which suggestion service supports for which algorithm.

### ISSUE THREAD

**Issue by c-bata** [kubeflow/katib#1147]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We will have two suggestion providers that support TPE after merged #1131.
So we should  update [here](https://github.com/kubeflow/katib/blob/master/docs/proposals/suggestion.md#algorithm-supports) to provide the following information:

* Which suggestion service supports for which algorithm? And which is the default?
* How to switch the suggestion service by `katib-config`.

TODO:

* [x] Kubeflow website (https://github.com/kubeflow/website/pull/1907)
* [ ] Katib developer-side documentation

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

See the https://github.com/kubeflow/katib/pull/1131#discussion_r407955790 for details.

**Comment by andreyvelich** [comment]
@c-bata Thanks for mentioning this.

I think, it is better to update Kubeflow Website with it, since users will need this information.
We want to have user-side documentation in the Website and developer-side documentation in Katib docs.
We can add this information when we update Katib images in Kubeflow Manifest repository.

What do you think @sarahmaddox @johnugeorge ?

**Comment by sarahmaddox** [comment]
Thanks @c-bata and @andreyvelich +1 to the recommendation to put the information on the website. This is the location of the user guide for Katib:
https://www.kubeflow.org/docs/components/hyperparameter-tuning/experiment/

**Comment by gaocegege** [comment]
Yeah I also recommend updating kubeflow docs.

**Comment by c-bata** [comment]
Hi, I submit a pull request to kubeflow/website:
https://github.com/kubeflow/website/pull/1907
