### ISSUE TITLE
Broken Examples on OpenShift

### ISSUE THREAD

**Issue by vpavlin** [kubeflow/katib#1206]
/kind bug

**What steps did you take and what happened:**
The examples are failing to run on OpenShift 4 because the containers run as an unprivileged user by default and the code in examples tries to write to inaccessible directories

**What did you expect to happen:**
Examples run and finish successfully

**Anything else you would like to add:**
I will provide a PR to fix this, but I am not sure what the flow should be since I need to change the Dockerfile and the example manifests - but since the manifests point to currently available images they'd stop working until new images are built.

So the question really is - do you want 2 PRs - 1. for Dockerfiles and 2. for manifests? Or should I just send a single PR?

**Environment:**

- Kubeflow version: 1.0
- Minikube version:
- Kubernetes version: (use `kubectl version`): OpenShift 4.4 (kubernetes v1.17.1)
- OS (e.g. from `/etc/os-release`): Fedora

**Comment by andreyvelich** [comment]
Hi @vpavlin, thank you for testing this.

I think you can make changes for Katib Manifest and Dockerfile in one PR since it is related to one problem.

During e2e testing, new build image will be used: https://github.com/kubeflow/katib/blob/master/test/scripts/v1beta1/check-katib-ready.sh#L63-L82.

If you also want to change training container images (e.g mnist example https://github.com/kubeflow/katib/tree/master/examples/v1beta1/mxnet-mnist), let me know, I will push new image to `docker.io/kubeflowkatib` repository.

Also, please create an issue to edit [kubeflow/manifest](https://github.com/kubeflow/manifests/tree/master/katib) repository, if it is needed. Ones we submit new image version, we should change manifest there also.

@gaocegege @johnugeorge Do we want to see this change in v1alpha3 and v1beta1 version?

**Comment by vpavlin** [comment]
Sorry @andreyvelich finally got back to this..PR is submitted, let me know what do you need from me to progress this
