### ISSUE TITLE
TPE suggestion gives same parameters sets in one getSuggestions call.

### ISSUE THREAD

**Issue by ever1022** [kubeflow/katib#1329]
/kind bug

**What steps did you take and what happened:**
Invoke getSuggestions( with request_number > 1) of HyperoptService with TPE algorithm,
it returns "request_number" sets of parameters set, but the parameters sets are all the same.

**What did you expect to happen:**
Return different parameters sets.

**Anything else you would like to add:**
For first run, TPE getSuggestions gives different parameters sets because of "random" suggestion,
and for the following, while request_number > 1, it used a loop for getting a trial every single round,
however the fmin.trials not updated, and hyperopt_algorithm return same trial every  in the loop.

**Environment:**

- Kubeflow version (`kfctl version`):
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`): v1.18.6
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 LTS

**Comment by andreyvelich** [comment]
Thank you to notice this @ever1022.
That is because [hyperopt `suggest`](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/tpe.py#L916) method produces only one Trial per request. We can't generate more than one Trial in one call.

I am not sure how we can update fmin with the generated Trial, since we don't have Trial results once it is created.

Can we use [`insert_trial_doc`](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/base.py#L442-L449) twice, first time when we generate new Trial, second when we update Trial with metric data?

/cc @gaocegege
