### ISSUE TITLE
Support for PBT (Population Based Training)

### ISSUE THREAD

**Issue by romeokienzler** [kubeflow/katib#1382]
/kind feature

**Support for PBT (Population Based Training)**
Ray tune recently came out with support for PBT, Deepmind showed exceptional performance. Are we considering to support PBT in Katib as well?

https://arxiv.org/abs/1711.09846
https://deepmind.com/blog/article/population-based-training-neural-networks

**Comment by andreyvelich** [comment]
Thank you for this information @romeokienzler, I think it's very exciting.

We definitely should investigate it and try to adopt it in Katib.
What do you think @gaocegege @johnugeorge ?

**Comment by gaocegege** [comment]
My colleague @ezioliao is working on our internal AutoML system and he is interested in this issue.

**Comment by ezioliao** [comment]
> My colleague @ezioliao is working on our internal AutoML system and he is interested in this issue.

PBT is already implemented in our own AutoML system and  I'm willing to solve it.

**Comment by andreyvelich** [comment]
That would be great!
Thank you @ezioliao, let us know if you need any help.

**Comment by andreyvelich** [comment]
@ezioliao Do you have time resources to work on this in 2021 ?
We can include PBT support in the 2021 Roadmap.

**Comment by hongjunGu2019** [comment]
@andreyvelich Hello, I am very interested in this proposal. May I ask when it will be launched and how can I participate

**Comment by romeokienzler** [comment]
@ezioliao

**Comment by johnugeorge** [comment]
@hongjunGu2019 Please see #1833

**Comment by hongjunGu2019** [comment]
> @hongjunGu2019 Please see #1833

Thanks

**Comment by hongjunGu2019** [comment]
> @hongjunGu2019 Please see #1833

Thanks

**Comment by david-thrower** [comment]
One enhancement to this which, I propose on this is an addition of a parameter to this, which a user can use to configure the training task to filter out invalid permutations of parameter values from each generation's trials, given rules like `minimum_skip_connection_depth` must be < `maximum_skip_connection_depth` , so as to filter out planned trials that would throw ValueErrors before they are executed. This would make more elaborate algorithms practical to run with the training op.

**Comment by johnugeorge** [comment]
@david-thrower We have an interface to add validation checks per suggestion algorithm. Ref: https://github.com/kubeflow/katib/pull/1924

**Comment by david-thrower** [comment]
@johnugeorge , I really appreciate you pointing that out, especiallyat this time of night in your time zone. If I am ever in town, I owe you a coffee drink. Sorry I missed that recent change. I'm glad to see this.  I may get more sleep this week than I thought. I will look into it. To clarify, this removes suggestions, not throws exceptions, right?

**Comment by johnugeorge** [comment]
`ValidateAlgorithmSettings` function is a common interface which can be implemented for any suggestion algorithm. If `ValidateAlgorithmSettings` fails, Katib controller changes `Suggestion `and `Experiment` status to `failed`.

https://github.com/kubeflow/katib/issues/1126

**Comment by david-thrower** [comment]
@johnugeorge I see. This is where the problem I am faced with lies. When I have a massive parameter space where as many as 1/4 of the values are invalid and may be trunning 1000+ trials on an IPU, TPU, or cluster of A100s, this requires me to set an very large maxFailedTrialCount to escape the run failing. If I do that, then I have to ignore any **other unforeseen** errors. What I had in mind was more of a preclusion from these suggestions being included in the oracles / metadata to begin with or being assigned a status that isn't seen as an error, that way the trial does not count towards maxFailedTrialCount, as this is a foreseen invalid trial these are inherently going to clutter the suggestions created by any algorithm having a permutation / mutation / rando selection step. I hope my clarification makes sense.

**Comment by johnugeorge** [comment]
I see. But the what is the real reason for this issue? Is it that the user configures invalid parameter range for an algorithm?

**Comment by david-thrower** [comment]
Example:

minimum_skip_connections: [1:10]
maximum_skip_conections: [1:10]

There are both valid and invalid permutations of these in this range (any permutation where minimum... is < maximum ... is valid, and not so, is invalid). Any single range  I could set to preclude invalid permutations: (e.g. setting minimum to [1:5] and maximum to [6:10]), this would eliminate many if not most valid permutations. (e.g. minimum = 7, maximum = 9 in this case ..). The NAS I am developing has many min_ max_ pairs in its prams, and each trail intrinsically needs them because of an ensemble - like setup that needs both the minimum and maximum to deduce the optimal solution(s) in this range (there may be an exponential number to sample from with the same narrow param range, there's no practical way to make the tariner take a straight number in lieu of the range) ... The only other workaround is to (within the train function), make the valid permutations of the pairs a list and do this:
{
```python3
# list[i][0] is minimum
# ist[i][1] is maximum
 
options = np.random.randint((100,2))
options = options[np.less(options[:,0],options[:,1])]

# options now looks like:
# [[1,2],
# [1,3] ...,
# [9,10]]

i = hp.Choice("min_and_max_skip_connections")

min_skip_conn = options[selection][0]
max_skip_conn = options[selection][1] 

# ... on to my code that parses the model ....

```
}

The problem with the approach above is that a [Bayesian | Hyperband | Genetic] algo can't extract a mathematical meaning to where in the space it is drawing possibilities. A human can't easily either. If I look at a rectangular coordinates plot, I can't draw a pattern of meaning in the engineered fused parameter "min_max_skip_connections" ... I hope this is making sense now. It is a very complex issue, but nonetheless, a real one (motivating me to write my own tuner, which I hope to not need to do, but have accepted that this may be the de facto option ... ).

**Comment by david-thrower** [comment]
@johnugeorge, I appreciate the attention to the issue. This is no doubt, a weird issue, but nonetheless, I can foresee this becoming a more common requirement as more complex algorithms become "production material".
