### ISSUE TITLE
Does katib support xgboost-operator?

### ISSUE THREAD

**Issue by 0as1s** [kubeflow/katib#1558]
Hi, I checked the repo and issues but did not find an answer. Can I use katib to find optimal hyperparameters for xgboost-operator(https://github.com/kubeflow/xgboost-operator)? 

I know katib can be used on xgboost. Can I simply modify the trialSpec part to run katib for xgboost-operator? Xgboost-operator's yaml file is similar to mpijob-horovod.yaml with one master and several  workers.

Thanks a lot!

**Comment by gaocegege** [comment]
I can be supported. But I do not it is supported now /cc @kubeflow/wg-automl-leads

**Comment by andreyvelich** [comment]
@0as1s Since Katib supports all Kubernetes CR, that can be easily supported by following this doc: https://www.kubeflow.org/docs/components/katib/trial-template/#use-custom-kubernetes-resource-as-a-trial-template.
It would be great if we implemented this support in default Katib controller settings.

**Comment by 0as1s** [comment]
Hi, @gaocegege @andreyvelich. Thank you for your answer!

**Comment by andreyvelich** [comment]
Let's keep this issue open and try to implement this feature in default Katib controller support, like we did with MPI operator.
/help
