### ISSUE TITLE
stdout metric collector failed

### ISSUE THREAD

**Issue by chenwenjun-github** [kubeflow/katib#1576]
/kind bug

**What steps did you take and what happened:**
![image](https://user-images.githubusercontent.com/46237364/125162483-b1516400-e1ba-11eb-8c33-f75f08adb553.png)

I use tfjob as trial's job, my tfjob has one ps, one chief, one worker, and the metric collector is stdout, but I find that the metrics-logger-and-collector container sometimes will become error, and the print like above, this isn't must present.
**But this will cause that the worker‘s  metric can't be collected.**

this error message in code like this:
![image](https://user-images.githubusercontent.com/46237364/125162603-6126d180-e1bb-11eb-9e12-109f85598bc5.png)

can you give me some advice to aviod this problem?

**What did you expect to happen:**
don't appear this error

**Environment:**

- katib version (`kfctl version`): v0.10.1
- Kubernetes version: (use `kubectl version`): 1.13

**Comment by chenwenjun-github** [comment]
I made some change on katib code like this:
![image](https://user-images.githubusercontent.com/46237364/125401937-65830280-e3e6-11eb-968c-b4e1e418b02f.png)
This reslove my problem, close this issue.

**Comment by andreyvelich** [comment]
Thank you for creating this @chenwenjun-github.
Yes, that should be an issue.
Maybe we should implement this change to the metrics collector source code?

WDYT @chenwenjun-github @gaocegege @johnugeorge ?

/priority p1
/help

**Comment by johnugeorge** [comment]
Sorry. I didn't understand the context very well. 

when will `metrics-logger-and-collector container ` error out?

**Comment by andreyvelich** [comment]
> Sorry. I didn't understand the context very well.
> 
> when will `metrics-logger-and-collector container ` error out?

This happens very rarely, when `psutil.Pids()` returns process, but when we try to create an object from this PID in [`psutil.NewProcess(pid)`](https://github.com/kubeflow/katib/blob/master/pkg/metricscollector/v1beta1/common/pns.go#L68) it can't be created.
My assumption that, this process might be stopped or finished before.

I think @chenwenjun-github solution above might work, since usually we wait only until [`mainPid` is complete](https://github.com/kubeflow/katib/blob/master/pkg/metricscollector/v1beta1/common/pns.go#L150).
I would only verify that `mainPid` contains the PID after `GetMainProcesses` finished.

We can discuss about it on our upcoming WG meeting tomorrow.
