### ISSUE TITLE
Katib example for feature store ML classfication

### ISSUE THREAD

**Issue by aniruddhachoudhury** [kubeflow/katib#1589]

**Comment by andreyvelich** [comment]
Thank you for creating this @aniruddhachoudhury.
I think we can add your example under: `./examples/v1beta1/pipelines/realtime-image-classification`, since we are planing to copy all our [Kubeflow Pipelines](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/kubeflow-katib) to the Katib repository.

What do you think @aniruddhachoudhury @gaocegege @johnugeorge ?

**Comment by aniruddhachoudhury** [comment]
Sure @andreyvelich  sounds good.

**Comment by gaocegege** [comment]
SGTM. Thanks for the issue
