### ISSUE TITLE
Example YAMLs runs failing

### ISSUE THREAD

**Issue by MasterofBisaster** [kubeflow/katib#1790]
/kind bug

**What steps did you take and what happened:**

Whenever I try to use one of the examples YAMLs (random, bayesian, etc) found in this repository, none of the runs succeded. All training containers related to the runs show errors, no output in logs. Most of the metrics-collector-container-logs show similiar outputs to the image below:
![image](https://user-images.githubusercontent.com/40423782/150842002-f54c31f3-ef46-4993-b4c5-ce1d9dfe0cbb.png)
While the training-container show an empty log:
![image](https://user-images.githubusercontent.com/40423782/150842079-e8ab7916-4ec4-471d-ab3d-531b97d3f88e.png)

Something to note is, that Istio is being used in this cluster, but as the Katib Docs suggest, istio-sidecar-injection is set to false in all of the YAMLs used.
**What did you expect to happen:**
That the runs of the example YAMLs would succeed as it is being shown in the Katib docs.
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Katib version (check the Katib controller image version): 0.12.0
- Kubeflow version: 1.4
- Kubernetes version: (`kubectl version`): 1.21.7
- OS (`uname -a`): On-Premise Linux

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by anencore94** [comment]
![image](https://user-images.githubusercontent.com/37469330/151643279-5ac608eb-cb24-4ea4-a762-165b6bfc883b.png)

I've tested several examples just now, However, It goes well in my test environments.

Could you exmplain more about your os, kubernetes, kubeflow installation ?
It seems to be you may use your cluster in wsl2 in windows from the screenshots.

I've tested with katib v0.12.0, kubeflow v1.4.0, kubernetes v1.21.1, minikube, ubuntu 20.04.
And used the official with changing namespace to istio-injection disabled, rather than disabling it from each katib experiment yaml.
![image](https://user-images.githubusercontent.com/37469330/151643368-2e6f23e5-81de-496e-b098-374978789209.png)

Also, could you add your results for `kubectl get pod -n <your-namespace>` to make sure ?
