### ISSUE TITLE
Bug: Succeeded trials are not loaded in the experiment graph  UI

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/katib#2013]
This issue is track the bug reported in  https://github.com/kubeflow/katib/pull/2001#issuecomment-1306377712

Actually, I found an issue with loading the visualized graph if the experiment is in "running" state (6 out of 10 trials are already succeeded but failed to load) :

/cc @shaowei-su 

/assign @elenzio9

**Comment by elenzio9** [comment]
The reason why this happens is because of this [line](https://github.com/kubeflow/katib/blob/b3c38073580e5545d875fd480a4cfdfdd8bf14ec/pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.ts#L255) and specifically the check: `!response.includes(',,')`, which is responsible for not displaying the graph when the backend response includes `,,`. That is, when a trial is in running state. However, this check doesn't consider the case where some of the trials are in succeeded state and the others are in running state. The graph should then show the succeeded trials, but currently the message is still displayed. 

One solution is to modify the check by taking into account the state of the trials. This way, when the first trial succeeds, the graph will appear.

**Comment by andreyvelich** [comment]
This was fixed, thanks!
