### ISSUE TITLE
Replace the tool of code generator for the gRPC API

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2141]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, we are generating codes for the gRPC API from the protocol buffers definition with [`znly/protoc`](https://hub.docker.com/r/znly/protoc/).

However, the image doesn't seem to be maintained since the latest image was published 4 years ago.

So, we should replace the toll with another one.

follow-up: #2140 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tenzen-y** [comment]
cc: @andreyvelich @johnugeorge

**Comment by tenzen-y** [comment]
Maybe, we can migrate the tool to the [`buf`](https://buf.build/).

**Comment by johnugeorge** [comment]
Agree. We should try it out

**Comment by shivas1516** [comment]
From the description provided in this issue, I understand that the existing code generation tool 'znly/protoc' is not maintained properly, and there's a need to migrate to another tool, which has been mentioned in this conversation as Buf. As this issue is marked as a good first issue and aligns with my skill level, I'm keen to contribute to resolving it. 

I'm seeking guidance and recommendations to get started on this task. Your assistance and response are invaluable to me. Looking forward to your input!

**Comment by tenzen-y** [comment]
> From the description provided in this issue, I understand that the existing code generation tool 'znly/protoc' is not maintained properly, and there's a need to migrate to another tool, which has been mentioned in this conversation as Buf. As this issue is marked as a good first issue and aligns with my skill level, I'm keen to contribute to resolving it. 
> 
> 
> 
> I'm seeking any guidance or recommendations to get started on this task. Your assistance and response are invaluable to me. Looking forward to your input!

@shivas1516 Your understanding is correct.
Feel free to open a PR. We’d be happy to review it.
