### ISSUE TITLE
Issue template "Kubeflow Katib Slack Channel" doesn't prompt you to register/get invited

### ISSUE THREAD

**Issue by orfeas-k** [kubeflow/katib#2343]
### What happened?

Hi there, I was trying to ask a question on slack so I clicked on that "issue template" and it didn't prompt anywhere to register. I had to google it in order to figure out I need to receive an invite. This makes for a sub-optimal UX.

### What did you expect to happen?

Have a link somewhere explaining that I have to request an invite

### Environment

N/A

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍

**Comment by orfeas-k** [comment]
BTW, is kubeflow-katib slack channel the place to ask something related to implementation or should I do it here? I don't see any activity there

**Comment by andreyvelich** [comment]
Thank you for creating this issue @orfeas-k!
That is because we recently migrated Kubeflow channels to the CNCF Slack.
Maybe you can't access it since you are not login to this Slack workspace ?
Should try to redirect folks to this URL to access #kubeflow-katib Slack channel: https://www.kubeflow.org/docs/about/community/#kubeflow-slack-channels ?

WDYT @orfeas-k @kubeflow/wg-training-leads ?

**Comment by tenzen-y** [comment]
We may want to add a CNCF Slack registration URL to the description.

> Ask the Katib community on Slack

**Comment by orfeas-k** [comment]
@andreyvelich: as @tenzen-y points out, I managed to access it after getting an invite from this link https://communityinviter.com/apps/cloud-native/cncf (found it through a google search) and following instructions.

Thus, +1 on the following
>We may want to add a CNCF Slack registration URL to the description.

Regarding my question, I'll post it on Slack.
