### ISSUE TITLE
Katib Experiment Graph and Metrics are not shown

### ISSUE THREAD

**Issue by ahmed-menshawy** [kubeflow/katib#680]
/kind bug

Hello, 

I was testing Katib v1alpha2:

- Used the deploy script to deploy katib to my existing k8s cluster(on-prem)
- Ran the tfjob example inside the examples folder of v1alpha2
- Experiment complete successfully

But the Katib dashboard is not showing the metrics graph when I click on the successfully complete experiment.

Screenshots:
-  https://ibb.co/drKjBNm
- https://ibb.co/y5WNLtc

**Comment by andreyvelich** [comment]
@ahmed-menshawy Thank you for your issue!
I think, the problem with the tf-event metrics collector, because, in the UI, I see empty results from the Katib mysql database for the TFjob experiment. 
Here https://github.com/kubeflow/katib/blob/master/examples/v1alpha2/tfjob-example.yaml#L13, we have `objectiveMetricName: accuracy_1`, but I checked the logs from the training containers of this example and saw, that we don't have this metric in the logs. 
I saw only this information: `Accuracy at step 990: 0.9572` 

@richardsliu @johnugeorge Any ideas how does tf-event metrics collector work? 
Does it follow the same idea as the general Katib metrics collector?

**Comment by johnugeorge** [comment]
@andreyvelich tf-event metrics collector parses the generated tf events file( instead of stdout as in case of default metric collector) and then writes to DB.

**Comment by johnugeorge** [comment]
@ahmed-menshawy Are you still seeing this issue?

**Comment by gaocegege** [comment]
/close

It is stale. But feel free to ask here.
