### ISSUE TITLE
metrics-collector service account doesn't exist in profile created namespace

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#841]
/kind bug

Using 0.6.2 I try to launch a Katib Experiment in the namespace associated with my profile.
The metrics collector jobs are not able to start because of the following error

```
Events:
  Type     Reason        Age                    From            Message
  ----     ------        ----                   ----            -------
  Warning  FailedCreate  2m22s (x5 over 4m53s)  job-controller  Error creating: pods "sauron-tune-191001-095415-rrfdmkpr-1569979500-" is forbidden: error looking up service account jlewi/metrics-collector: serviceaccount "metrics-collector" not found
```

It looks like the problem is that the metrics collector jobs are trying to use the metrics-collector service account which doesn't automatically exist in my namespace.

There are at least two ways to fix this

1. Have profile controller create that service account
1. Use a different service account that is created by the profile controller

## Work Around

To work around this issue you can manually create the service account and binding.

```
kubectl -n ${NAMESPACE} create serviceaccount metrics-collector

kubectl -n ${NAMESPACE} create rolebinding metrics-collector --clusterrole=metrics-collector --serviceaccount=${NAMESPACE}:metrics-collector
```

/cc @johnugeorge @richardsliu

**Comment by johnugeorge** [comment]
@jlewi  

This is a known design limitation with v1alpha2 API.  Corresponding issue is https://github.com/kubeflow/kubeflow/issues/2311 

However, this issue is resolved in 0.7 as we have a new metric collector design. It is no more having separate metric collector cronjob. Instead, there is a metric collector side car, which collects the metrics and writes to DB. Details are added in https://github.com/kubeflow/katib/blob/master/docs/proposals/metrics-collector.md 

In 0.7, pod level injector is currently implemented.(See specific section https://github.com/kubeflow/katib/blob/master/docs/proposals/metrics-collector.md#mutating-webhook)  This requires one additional configuration of adding` katib-metrics-collector-injection=enabled` label  to all namespaces where Katib Experiment has to be launched. This label can be added when namespace is created by profile.
eg:  https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/0-namespace.yaml#L6

**Comment by jlewi** [comment]
Thanks @johnugeorge what if people what if people want to directly instrument their code to report metrics rather than printing to stdout and relying on stdout to collect metrics?

In particular, now that we have KFMD, if I add a logging statement to record metrics to KFMD, can Katib get the metrics directly from KFMD?

/cc @richardsliu @zhenghuiwang

**Comment by johnugeorge** [comment]
The design doc supports push based approach too(logging directly from training container)  - https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/common/v1alpha3/common_types.go#L133 

DB backend is made pluggable in this release(https://github.com/kubeflow/katib/pull/760) . Inorder to support KFMD(or any other DB), we just need to implement the KatibDBInterface(https://github.com/kubeflow/katib/blob/master/pkg/db/v1alpha3/common/kdb.go#L7)  -- Basically, Init DB, Get metric, Create metric and Delete metric functions

Currently, mysql is the only supported one. Refer:  https://github.com/kubeflow/katib/blob/master/pkg/db/v1alpha3/mysql/mysql.go  It should be easy to integrate any new DB backend now.

**Comment by johnugeorge** [comment]
Shall we close this as it is resolved in v1alpha3

**Comment by gaocegege** [comment]
I think so.

/close
