### ISSUE TITLE
ReadWriteMany unsupported for PVCs on GCP

### ISSUE THREAD

**Issue by texasmichelle** [kubeflow/katib#917]
/kind bug

**What steps did you take and what happened:**
When creating [tfevent-pvc](https://github.com/kubeflow/katib/blob/master/examples/v1alpha2/tfevent-volume/tfevent-pvc.yaml), it fails on GCP with this error:
`Failed to provision volume with StorageClass "standard": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce ReadOnlyMany] are supported`

**What did you expect to happen:**
The PVC to be created without errors.

**Anything else you would like to add:**
Since C2D doesn't support v0.7.0 yet, this version (v1alpha2) should work on GCP without failures.

**Environment:**

- Kubeflow version: v0.6.2 (latest in C2D)
- Minikube version: n/a
- Kubernetes version: (use `kubectl version`): client: v1.13.11, server: v1.12.10-gke.17
- OS (e.g. from `/etc/os-release`): MacOS v10.14.6

**Comment by gaocegege** [comment]
Thanks for the issue.

/cc @hougangliu

**Comment by texasmichelle** [comment]
Fix incoming 🚀

**Comment by hougangliu** [comment]
this example is for minikube assuming that the PVC with `ReadWriteMany` can be created
Since multiple trials/jobs can run in parallel to write TensorFlow event to the PV, and multiple tf-metricscollector Pod will read the data, so the PVC must be  `ReadWriteMany`.
I think default  GCP storage class is gcePersistentDisk driver, which can only be mounted by a single consumer in read-write mode - no simultaneous writers allowed.

@texasmichelle  So I think you have to make your cluster support `ReadWriteMany` PVC somehow, maybe https://github.com/mappedinn/kubernetes-nfs-volume-on-gke helps.

BTW, just curious about what is C2D?

**Comment by texasmichelle** [comment]
Oh - we only have examples for minikube? Because HP tuning is so resource-intensive and I've had trouble just getting barebones KF to run on its own locally, it didn't even occur to me to try minikube. I think it would be worthwhile to have a cloud version of the examples.

@richardsliu what do you suggest for pvc config on gke?

C2D = [click-to-deploy](https://deploy.kubeflow.cloud)

**Comment by hougangliu** [comment]
sorry to mislead you, the example can work in most platforms including minikube, and in most platform, `ReadWriteMany` PVC can be created.
I think GCP also should have solution to support `ReadWriteMany` PVC (for now I guess default storageclass is gcePersistentDisk, can you try if there is other storageclass in GCP to support `ReadWriteMany`, if there is, just make the example pvc storageclass as the one).

**Comment by gaocegege** [comment]
ReadWriteMany is common, I think GCP should support it. Ref https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

**Comment by richardsliu** [comment]
Katib-mysql is ReadWriteOnce, how does it work?
https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/pv/pv.yaml

**Comment by richardsliu** [comment]
Standard storage class provisoner is GKE PD which doesn't support ReadWriteMany:
```
NAME                 PROVISIONER            AGE
standard (default)   kubernetes.io/gce-pd   6d2h
```
https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

So another solution is to try a different storage class.

**Comment by hougangliu** [comment]
> Katib-mysql is ReadWriteOnce, how does it work?
> https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/pv/pv.yaml

Only one Pod is running for katib-mysql.

**Comment by vpavlin** [comment]
It is a common problem among cloud provider and storage backends in general. There are some heavily used (GCP PD, AWS EBS, Ceph) which do not support `ReadWriteMany` specifically because they won't allow you to attach one block device to multiple nodes, thus if you scale up and scheduler distributes the load, containers won't start because the volume will not be able to attach to multiple nodes.

Maybe it would make sense to note that in the example or Katib documentation that `ReadWriteMany` for storage backend is required (e.g. NFS), or think about a different option like using object storage somehow.

**Comment by gaocegege** [comment]
@vpavlin 's advice SGTM.

For katib-mysql, I think the users should have other choices to deploy a SQL DB.

For trial-used volumes,  if we do not have a ReadWriteMany volume, the parallelism will be limited.

**Comment by andreyvelich** [comment]
We don't have Trial volumes currently.
We can close it.
Feel free to re-open if you see this problem again.

**Comment by sebastianbarry-sms** [comment]
/reopen I've been working on a vSphere cluster and have noticed the same issue. 

`invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported`

Using: 
` kubernetes.io/vsphere-volume`

**Comment by markbluhm** [comment]
I am also running into this with GKE 1.23. Here is the specific `kubectl version` for the server
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8-gke.1900", GitCommit:"79209257257c051b27df67c567755783eda93353", GitTreeState:"clean", BuildDate:"2022-07-15T09:23:51Z", GoVersion:"go1.17.11b7", Compiler:"gc", Platform:"linux/amd64"}
```
