### ISSUE TITLE
[UI Feature] Select namespace from Kubeflow Central Dashboard

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#972]
/kind feature

We need to have connection between Katib UI and Kubeflow Central Dashboard.
If user select namespace in Central Dashboard:
1. User should see experiments only in selected namespace
2. User should be able to create experiments only in selected namespace

If you have any thoughts about other functionalities related to this let me know
@johnugeorge @gaocegege @hougangliu 

/assign @andreyvelich

**Comment by avdaredevil** [comment]
This communication channel already exists between Notebooks UI and Central-Dashboard via an [SDK we provide](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard#client-side-library):
- It allows the client to detect whether it's in running inside central-dashboard or as an independent page
- Allows client to hook into namespace change events that are passed from CDash.

I'd also recommend updating the UI to match the [style-guide](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard#style-guide) published, so that the entire experience feels more uniform.

This allow

**Comment by gaocegege** [comment]
LGTM
